# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Youngil Ko
description: >- # this means to ignore newlines until "baseurl:"
  Youngil Ko's Website
baseurl: "" # the subpath of the site
url: "https://youngilko.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
    - name: CV
      slug: /assets/pdf/CV_YoungilKo.pdf

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: youngil.ko@kaist.ac.kr
      link: mailto:youngil.ko@kaist.ac.kr

  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/youngilko
    - name: GoogleScholar
      link: https://scholar.google.com/citations?user=OTSlFr4AAAAJ&hl=en

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
